//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gssdb_cards : DbContext
    {
        public gssdb_cards()
            : base("name=gssdb_cards")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<DNN_Affiliates> DNN_Affiliates { get; set; }
        public DbSet<DNN_AnonymousUsers> DNN_AnonymousUsers { get; set; }
        public DbSet<DNN_Assemblies> DNN_Assemblies { get; set; }
        public DbSet<DNN_Authentication> DNN_Authentication { get; set; }
        public DbSet<DNN_Banners> DNN_Banners { get; set; }
        public DbSet<DNN_Classification> DNN_Classification { get; set; }
        public DbSet<DNN_DesktopModules> DNN_DesktopModules { get; set; }
        public DbSet<DNN_EventLog> DNN_EventLog { get; set; }
        public DbSet<DNN_EventLogConfig> DNN_EventLogConfig { get; set; }
        public DbSet<DNN_EventLogTypes> DNN_EventLogTypes { get; set; }
        public DbSet<DNN_EventQueue> DNN_EventQueue { get; set; }
        public DbSet<DNN_Files> DNN_Files { get; set; }
        public DbSet<DNN_FolderPermission> DNN_FolderPermission { get; set; }
        public DbSet<DNN_Folders> DNN_Folders { get; set; }
        public DbSet<DNN_HostSettings> DNN_HostSettings { get; set; }
        public DbSet<DNN_HtmlText> DNN_HtmlText { get; set; }
        public DbSet<DNN_Links> DNN_Links { get; set; }
        public DbSet<DNN_Lists> DNN_Lists { get; set; }
        public DbSet<DNN_ModuleControls> DNN_ModuleControls { get; set; }
        public DbSet<DNN_ModuleDefinitions> DNN_ModuleDefinitions { get; set; }
        public DbSet<DNN_ModulePermission> DNN_ModulePermission { get; set; }
        public DbSet<DNN_Modules> DNN_Modules { get; set; }
        public DbSet<DNN_ModuleSettings> DNN_ModuleSettings { get; set; }
        public DbSet<DNN_Packages> DNN_Packages { get; set; }
        public DbSet<DNN_PackageTypes> DNN_PackageTypes { get; set; }
        public DbSet<DNN_Permission> DNN_Permission { get; set; }
        public DbSet<DNN_PortalAlias> DNN_PortalAlias { get; set; }
        public DbSet<DNN_PortalDesktopModules> DNN_PortalDesktopModules { get; set; }
        public DbSet<DNN_Portals> DNN_Portals { get; set; }
        public DbSet<DNN_Profile> DNN_Profile { get; set; }
        public DbSet<DNN_ProfilePropertyDefinition> DNN_ProfilePropertyDefinition { get; set; }
        public DbSet<DNN_RoleGroups> DNN_RoleGroups { get; set; }
        public DbSet<DNN_Roles> DNN_Roles { get; set; }
        public DbSet<DNN_Schedule> DNN_Schedule { get; set; }
        public DbSet<DNN_ScheduleHistory> DNN_ScheduleHistory { get; set; }
        public DbSet<DNN_ScheduleItemSettings> DNN_ScheduleItemSettings { get; set; }
        public DbSet<DNN_SearchCommonWords> DNN_SearchCommonWords { get; set; }
        public DbSet<DNN_SearchIndexer> DNN_SearchIndexer { get; set; }
        public DbSet<DNN_SearchItem> DNN_SearchItem { get; set; }
        public DbSet<DNN_SearchItemWord> DNN_SearchItemWord { get; set; }
        public DbSet<DNN_SearchItemWordPosition> DNN_SearchItemWordPosition { get; set; }
        public DbSet<DNN_SearchWord> DNN_SearchWord { get; set; }
        public DbSet<DNN_SiteLog> DNN_SiteLog { get; set; }
        public DbSet<DNN_Skins> DNN_Skins { get; set; }
        public DbSet<DNN_SystemMessages> DNN_SystemMessages { get; set; }
        public DbSet<DNN_TabModules> DNN_TabModules { get; set; }
        public DbSet<DNN_TabModuleSettings> DNN_TabModuleSettings { get; set; }
        public DbSet<DNN_TabPermission> DNN_TabPermission { get; set; }
        public DbSet<DNN_Tabs> DNN_Tabs { get; set; }
        public DbSet<DNN_UrlLog> DNN_UrlLog { get; set; }
        public DbSet<DNN_Urls> DNN_Urls { get; set; }
        public DbSet<DNN_UrlTracking> DNN_UrlTracking { get; set; }
        public DbSet<DNN_UserAuthentication> DNN_UserAuthentication { get; set; }
        public DbSet<DNN_UserPortals> DNN_UserPortals { get; set; }
        public DbSet<DNN_UserProfile> DNN_UserProfile { get; set; }
        public DbSet<DNN_UserRoles> DNN_UserRoles { get; set; }
        public DbSet<DNN_Users> DNN_Users { get; set; }
        public DbSet<DNN_UsersOnline> DNN_UsersOnline { get; set; }
        public DbSet<DNN_VendorClassification> DNN_VendorClassification { get; set; }
        public DbSet<DNN_Vendors> DNN_Vendors { get; set; }
        public DbSet<DNN_Version> DNN_Version { get; set; }
        public DbSet<GSS_Banks> GSS_Banks { get; set; }
        public DbSet<GSS_BranchStaff> GSS_BranchStaff { get; set; }
        public DbSet<GSS_BusinessOffices> GSS_BusinessOffices { get; set; }
        public DbSet<GSS_Cards_ATMCustodians> GSS_Cards_ATMCustodians { get; set; }
        public DbSet<GSS_Cards_Disputes_Logs> GSS_Cards_Disputes_Logs { get; set; }
        public DbSet<GSS_Cards_Disputes_NEW> GSS_Cards_Disputes_NEW { get; set; }
        public DbSet<GSS_Cards_JobRuns> GSS_Cards_JobRuns { get; set; }
        public DbSet<GSS_Cards_Jobs> GSS_Cards_Jobs { get; set; }
        public DbSet<GSS_Cards_JobTypes> GSS_Cards_JobTypes { get; set; }
        public DbSet<GSS_Cards_Schedules> GSS_Cards_Schedules { get; set; }
        public DbSet<GSS_Cards_Terminals> GSS_Cards_Terminals { get; set; }
        public DbSet<GSS_Cards_Transactions> GSS_Cards_Transactions { get; set; }
        public DbSet<GSS_Cheques> GSS_Cheques { get; set; }
        public DbSet<GSS_Cheques_CautionReasons> GSS_Cheques_CautionReasons { get; set; }
        public DbSet<GSS_Cheques_ClearingSessions> GSS_Cheques_ClearingSessions { get; set; }
        public DbSet<GSS_Cheques_CutOffTimes> GSS_Cheques_CutOffTimes { get; set; }
        public DbSet<GSS_Cheques_DeliveryNotes> GSS_Cheques_DeliveryNotes { get; set; }
        public DbSet<GSS_Cheques_Details> GSS_Cheques_Details { get; set; }
        public DbSet<GSS_Cheques_FinacleReportFiles> GSS_Cheques_FinacleReportFiles { get; set; }
        public DbSet<GSS_Cheques_Logs> GSS_Cheques_Logs { get; set; }
        public DbSet<GSS_Cheques_PredefinedRejectReasons> GSS_Cheques_PredefinedRejectReasons { get; set; }
        public DbSet<GSS_Cheques_RejectionReasons> GSS_Cheques_RejectionReasons { get; set; }
        public DbSet<GSS_Cheques_RejectReasons> GSS_Cheques_RejectReasons { get; set; }
        public DbSet<GSS_Cheques_ReplacementScans> GSS_Cheques_ReplacementScans { get; set; }
        public DbSet<GSS_Cheques_ReturnReasons> GSS_Cheques_ReturnReasons { get; set; }
        public DbSet<GSS_Cheques_Scans> GSS_Cheques_Scans { get; set; }
        public DbSet<GSS_Cheques_ScansHistories> GSS_Cheques_ScansHistories { get; set; }
        public DbSet<GSS_Cheques_ScansWorkflows> GSS_Cheques_ScansWorkflows { get; set; }
        public DbSet<GSS_Cheques_Schedules> GSS_Cheques_Schedules { get; set; }
        public DbSet<GSS_Cheques_SupportingDocuments> GSS_Cheques_SupportingDocuments { get; set; }
        public DbSet<GSS_Cheques_Tags> GSS_Cheques_Tags { get; set; }
        public DbSet<GSS_Cheques_TagsDefinitions> GSS_Cheques_TagsDefinitions { get; set; }
        public DbSet<GSS_Clusters> GSS_Clusters { get; set; }
        public DbSet<GSS_DocumentAttachments> GSS_DocumentAttachments { get; set; }
        public DbSet<GSS_DocumentLog> GSS_DocumentLog { get; set; }
        public DbSet<GSS_DocumentQueues> GSS_DocumentQueues { get; set; }
        public DbSet<GSS_Documents> GSS_Documents { get; set; }
        public DbSet<GSS_DocumentTypes> GSS_DocumentTypes { get; set; }
        public DbSet<GSS_GroupHeads> GSS_GroupHeads { get; set; }
        public DbSet<GSS_HeadsOfOperations> GSS_HeadsOfOperations { get; set; }
        public DbSet<GSS_Holidays> GSS_Holidays { get; set; }
        public DbSet<GSS_RegionalBanks> GSS_RegionalBanks { get; set; }
        public DbSet<GSS_RejectionReasons> GSS_RejectionReasons { get; set; }
        public DbSet<GSS_ReportRuns> GSS_ReportRuns { get; set; }
        public DbSet<GSS_TeamClusters> GSS_TeamClusters { get; set; }
        public DbSet<GSS_Teams> GSS_Teams { get; set; }
        public DbSet<GSS_TeamUsers> GSS_TeamUsers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<GSS_Gasper> GSS_Gasper { get; set; }
        public DbSet<BusinessOfficesView> BusinessOfficesViews { get; set; }
        public DbSet<DNN_vw_FolderPermissions> DNN_vw_FolderPermissions { get; set; }
        public DbSet<DNN_vw_Lists> DNN_vw_Lists { get; set; }
        public DbSet<DNN_vw_ModulePermissions> DNN_vw_ModulePermissions { get; set; }
        public DbSet<DNN_vw_Modules> DNN_vw_Modules { get; set; }
        public DbSet<DNN_vw_Portals> DNN_vw_Portals { get; set; }
        public DbSet<DNN_vw_TabPermissions> DNN_vw_TabPermissions { get; set; }
        public DbSet<DNN_vw_Tabs> DNN_vw_Tabs { get; set; }
        public DbSet<DNN_vw_Users> DNN_vw_Users { get; set; }
        public DbSet<GSS_BCMs> GSS_BCMs { get; set; }
        public DbSet<GSS_BOMs> GSS_BOMs { get; set; }
        public DbSet<GSS_Cards_Disputes> GSS_Cards_Disputes { get; set; }
        public DbSet<GSS_Cards_Disputes_IDV> GSS_Cards_Disputes_IDV { get; set; }
        public DbSet<GSS_Cards_Report> GSS_Cards_Report { get; set; }
        public DbSet<GSS_Cheques_NACS_OUT_Cheques> GSS_Cheques_NACS_OUT_Cheques { get; set; }
        public DbSet<GSS_Cheques_OUT_CBN_Cheques> GSS_Cheques_OUT_CBN_Cheques { get; set; }
        public DbSet<GSS_Cheques_Queues> GSS_Cheques_Queues { get; set; }
        public DbSet<GSS_Cheques_Transactions> GSS_Cheques_Transactions { get; set; }
        public DbSet<GSS_CSOs> GSS_CSOs { get; set; }
        public DbSet<GSS_Documents_View> GSS_Documents_View { get; set; }
        public DbSet<GSS_DocumentsOutsideTAT> GSS_DocumentsOutsideTAT { get; set; }
        public DbSet<GSS_DocumentsReceived> GSS_DocumentsReceived { get; set; }
        public DbSet<GSS_DocumentsWithinTAT> GSS_DocumentsWithinTAT { get; set; }
        public DbSet<GSS_Teams_View> GSS_Teams_View { get; set; }
        public DbSet<GSS_TeamView> GSS_TeamView { get; set; }
        public DbSet<GSS_TransactionActivityReportView> GSS_TransactionActivityReportView { get; set; }
        public DbSet<GSS_UserView> GSS_UserView { get; set; }
        public DbSet<UserView> UserViews { get; set; }
        public DbSet<vw_aspnet_Applications> vw_aspnet_Applications { get; set; }
        public DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public DbSet<vw_aspnet_Profiles> vw_aspnet_Profiles { get; set; }
        public DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
    }
}
