//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_UrlTracking
    {
        public DNN_UrlTracking()
        {
            this.DNN_UrlLog = new HashSet<DNN_UrlLog>();
        }
    
        public int UrlTrackingID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string Url { get; set; }
        public string UrlType { get; set; }
        public int Clicks { get; set; }
        public Nullable<System.DateTime> LastClick { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool LogActivity { get; set; }
        public bool TrackClicks { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public bool NewWindow { get; set; }
    
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_UrlLog> DNN_UrlLog { get; set; }
    }
}
