//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Tabs
    {
        public DNN_Tabs()
        {
            this.DNN_TabModules = new HashSet<DNN_TabModules>();
            this.DNN_TabPermission = new HashSet<DNN_TabPermission>();
            this.DNN_Tabs1 = new HashSet<DNN_Tabs>();
        }
    
        public int TabID { get; set; }
        public int TabOrder { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string TabName { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Level { get; set; }
        public string IconFile { get; set; }
        public bool DisableLink { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public bool IsDeleted { get; set; }
        public string Url { get; set; }
        public string SkinSrc { get; set; }
        public string ContainerSrc { get; set; }
        public string TabPath { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public string PageHeadText { get; set; }
        public bool IsSecure { get; set; }
    
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_TabModules> DNN_TabModules { get; set; }
        public virtual ICollection<DNN_TabPermission> DNN_TabPermission { get; set; }
        public virtual ICollection<DNN_Tabs> DNN_Tabs1 { get; set; }
        public virtual DNN_Tabs DNN_Tabs2 { get; set; }
    }
}
