//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Modules
    {
        public DNN_Modules()
        {
            this.DNN_Links = new HashSet<DNN_Links>();
            this.DNN_ModulePermission = new HashSet<DNN_ModulePermission>();
            this.DNN_ModuleSettings = new HashSet<DNN_ModuleSettings>();
            this.DNN_SearchItem = new HashSet<DNN_SearchItem>();
            this.DNN_TabModules = new HashSet<DNN_TabModules>();
        }
    
        public int ModuleID { get; set; }
        public int ModuleDefID { get; set; }
        public string ModuleTitle { get; set; }
        public bool AllTabs { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> InheritViewPermissions { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PortalID { get; set; }
    
        public virtual DNN_HtmlText DNN_HtmlText { get; set; }
        public virtual ICollection<DNN_Links> DNN_Links { get; set; }
        public virtual DNN_ModuleDefinitions DNN_ModuleDefinitions { get; set; }
        public virtual ICollection<DNN_ModulePermission> DNN_ModulePermission { get; set; }
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_ModuleSettings> DNN_ModuleSettings { get; set; }
        public virtual ICollection<DNN_SearchItem> DNN_SearchItem { get; set; }
        public virtual ICollection<DNN_TabModules> DNN_TabModules { get; set; }
    }
}
