//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_vw_Lists
    {
        public int EntryID { get; set; }
        public string ListName { get; set; }
        public string Value { get; set; }
        public string Text { get; set; }
        public int Level { get; set; }
        public int SortOrder { get; set; }
        public int DefinitionID { get; set; }
        public int ParentID { get; set; }
        public string Description { get; set; }
        public int PortalID { get; set; }
        public bool SystemList { get; set; }
        public string ParentKey { get; set; }
        public string Parent { get; set; }
        public string ParentList { get; set; }
        public Nullable<int> MaxSortOrder { get; set; }
        public Nullable<int> EntryCount { get; set; }
        public Nullable<int> HasChildren { get; set; }
    }
}
