//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_VendorClassification
    {
        public int VendorClassificationId { get; set; }
        public int VendorId { get; set; }
        public int ClassificationId { get; set; }
    
        public virtual DNN_Classification DNN_Classification { get; set; }
        public virtual DNN_Vendors DNN_Vendors { get; set; }
    }
}
