//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_EventLogConfig
    {
        public DNN_EventLogConfig()
        {
            this.DNN_EventLog = new HashSet<DNN_EventLog>();
        }
    
        public int ID { get; set; }
        public string LogTypeKey { get; set; }
        public Nullable<int> LogTypePortalID { get; set; }
        public bool LoggingIsActive { get; set; }
        public int KeepMostRecent { get; set; }
        public bool EmailNotificationIsActive { get; set; }
        public Nullable<int> NotificationThreshold { get; set; }
        public Nullable<int> NotificationThresholdTime { get; set; }
        public Nullable<int> NotificationThresholdTimeType { get; set; }
        public string MailFromAddress { get; set; }
        public string MailToAddress { get; set; }
    
        public virtual ICollection<DNN_EventLog> DNN_EventLog { get; set; }
        public virtual DNN_EventLogTypes DNN_EventLogTypes { get; set; }
    }
}
