//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Permission
    {
        public DNN_Permission()
        {
            this.DNN_FolderPermission = new HashSet<DNN_FolderPermission>();
            this.DNN_ModulePermission = new HashSet<DNN_ModulePermission>();
            this.DNN_TabPermission = new HashSet<DNN_TabPermission>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionCode { get; set; }
        public int ModuleDefID { get; set; }
        public string PermissionKey { get; set; }
        public string PermissionName { get; set; }
    
        public virtual ICollection<DNN_FolderPermission> DNN_FolderPermission { get; set; }
        public virtual ICollection<DNN_ModulePermission> DNN_ModulePermission { get; set; }
        public virtual ICollection<DNN_TabPermission> DNN_TabPermission { get; set; }
    }
}
