//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Packages
    {
        public DNN_Packages()
        {
            this.DNN_Assemblies = new HashSet<DNN_Assemblies>();
        }
    
        public int PackageID { get; set; }
        public string Name { get; set; }
        public string FriendlyName { get; set; }
        public string Description { get; set; }
        public string PackageType { get; set; }
        public string Version { get; set; }
        public string License { get; set; }
        public string Manifest { get; set; }
    
        public virtual ICollection<DNN_Assemblies> DNN_Assemblies { get; set; }
    }
}
