//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_SearchItem
    {
        public DNN_SearchItem()
        {
            this.DNN_SearchItemWord = new HashSet<DNN_SearchItemWord>();
        }
    
        public int SearchItemID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Author { get; set; }
        public System.DateTime PubDate { get; set; }
        public int ModuleId { get; set; }
        public string SearchKey { get; set; }
        public string Guid { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> ImageFileId { get; set; }
    
        public virtual DNN_Modules DNN_Modules { get; set; }
        public virtual ICollection<DNN_SearchItemWord> DNN_SearchItemWord { get; set; }
    }
}
