//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_SearchWord
    {
        public DNN_SearchWord()
        {
            this.DNN_SearchItemWord = new HashSet<DNN_SearchItemWord>();
        }
    
        public int SearchWordsID { get; set; }
        public string Word { get; set; }
        public Nullable<bool> IsCommon { get; set; }
        public int HitCount { get; set; }
    
        public virtual ICollection<DNN_SearchItemWord> DNN_SearchItemWord { get; set; }
    }
}
