//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Profile
    {
        public int ProfileId { get; set; }
        public int UserId { get; set; }
        public int PortalId { get; set; }
        public string ProfileData { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual DNN_Users DNN_Users { get; set; }
    }
}
