//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Vendors
    {
        public DNN_Vendors()
        {
            this.DNN_Affiliates = new HashSet<DNN_Affiliates>();
            this.DNN_Banners = new HashSet<DNN_Banners>();
            this.DNN_VendorClassification = new HashSet<DNN_VendorClassification>();
        }
    
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public int ClickThroughs { get; set; }
        public int Views { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LogoFile { get; set; }
        public string KeyWords { get; set; }
        public string Unit { get; set; }
        public bool Authorized { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cell { get; set; }
    
        public virtual ICollection<DNN_Affiliates> DNN_Affiliates { get; set; }
        public virtual ICollection<DNN_Banners> DNN_Banners { get; set; }
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_VendorClassification> DNN_VendorClassification { get; set; }
    }
}
