//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Folders
    {
        public DNN_Folders()
        {
            this.DNN_Files = new HashSet<DNN_Files>();
            this.DNN_FolderPermission = new HashSet<DNN_FolderPermission>();
        }
    
        public int FolderID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string FolderPath { get; set; }
        public int StorageLocation { get; set; }
        public bool IsProtected { get; set; }
        public bool IsCached { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<DNN_Files> DNN_Files { get; set; }
        public virtual ICollection<DNN_FolderPermission> DNN_FolderPermission { get; set; }
        public virtual DNN_Portals DNN_Portals { get; set; }
    }
}
