//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_vw_Modules
    {
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> TabId { get; set; }
        public Nullable<int> TabModuleId { get; set; }
        public int ModuleID { get; set; }
        public int ModuleDefID { get; set; }
        public Nullable<int> ModuleOrder { get; set; }
        public string PaneName { get; set; }
        public string ModuleTitle { get; set; }
        public Nullable<int> CacheTime { get; set; }
        public string Alignment { get; set; }
        public string Color { get; set; }
        public string Border { get; set; }
        public string IconFile { get; set; }
        public bool AllTabs { get; set; }
        public Nullable<int> Visibility { get; set; }
        public bool IsDeleted { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ContainerSrc { get; set; }
        public Nullable<bool> DisplayTitle { get; set; }
        public Nullable<bool> DisplayPrint { get; set; }
        public Nullable<bool> DisplaySyndicate { get; set; }
        public Nullable<bool> InheritViewPermissions { get; set; }
        public int DesktopModuleID { get; set; }
        public string FriendlyName { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public bool IsPremium { get; set; }
        public bool IsAdmin { get; set; }
        public string BusinessControllerClass { get; set; }
        public string FolderName { get; set; }
        public string ModuleName { get; set; }
        public int SupportedFeatures { get; set; }
        public string CompatibleVersions { get; set; }
        public string Dependencies { get; set; }
        public string Permissions { get; set; }
        public int DefaultCacheTime { get; set; }
        public int ModuleControlId { get; set; }
        public string ControlSrc { get; set; }
        public int ControlType { get; set; }
        public string ControlTitle { get; set; }
        public string HelpURL { get; set; }
        public bool SupportsPartialRendering { get; set; }
    }
}
