//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_ProfilePropertyDefinition
    {
        public DNN_ProfilePropertyDefinition()
        {
            this.DNN_UserProfile = new HashSet<DNN_UserProfile>();
        }
    
        public int PropertyDefinitionID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> ModuleDefID { get; set; }
        public bool Deleted { get; set; }
        public int DataType { get; set; }
        public string DefaultValue { get; set; }
        public string PropertyCategory { get; set; }
        public string PropertyName { get; set; }
        public int Length { get; set; }
        public bool Required { get; set; }
        public string ValidationExpression { get; set; }
        public int ViewOrder { get; set; }
        public bool Visible { get; set; }
    
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_UserProfile> DNN_UserProfile { get; set; }
    }
}
