//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Banners
    {
        public int BannerId { get; set; }
        public int VendorId { get; set; }
        public string ImageFile { get; set; }
        public string BannerName { get; set; }
        public int Impressions { get; set; }
        public double CPM { get; set; }
        public int Views { get; set; }
        public int ClickThroughs { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BannerTypeId { get; set; }
        public string Description { get; set; }
        public string GroupName { get; set; }
        public bool Criteria { get; set; }
        public string URL { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual DNN_Vendors DNN_Vendors { get; set; }
    }
}
