//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_Users
    {
        public DNN_Users()
        {
            this.DNN_FolderPermission = new HashSet<DNN_FolderPermission>();
            this.DNN_ModulePermission = new HashSet<DNN_ModulePermission>();
            this.DNN_Profile = new HashSet<DNN_Profile>();
            this.DNN_TabPermission = new HashSet<DNN_TabPermission>();
            this.DNN_UserAuthentication = new HashSet<DNN_UserAuthentication>();
            this.DNN_UserPortals = new HashSet<DNN_UserPortals>();
            this.DNN_UserProfile = new HashSet<DNN_UserProfile>();
            this.DNN_UserRoles = new HashSet<DNN_UserRoles>();
            this.DNN_UsersOnline = new HashSet<DNN_UsersOnline>();
            this.GSS_BranchStaff = new HashSet<GSS_BranchStaff>();
            this.GSS_DocumentAttachments = new HashSet<GSS_DocumentAttachments>();
            this.GSS_DocumentLog = new HashSet<GSS_DocumentLog>();
            this.GSS_DocumentQueues = new HashSet<GSS_DocumentQueues>();
            this.GSS_GroupHeads = new HashSet<GSS_GroupHeads>();
            this.GSS_HeadsOfOperations = new HashSet<GSS_HeadsOfOperations>();
            this.GSS_TeamUsers = new HashSet<GSS_TeamUsers>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public bool UpdatePassword { get; set; }
        public int Availability { get; set; }
        public int MaxQueue { get; set; }
    
        public virtual ICollection<DNN_FolderPermission> DNN_FolderPermission { get; set; }
        public virtual ICollection<DNN_ModulePermission> DNN_ModulePermission { get; set; }
        public virtual ICollection<DNN_Profile> DNN_Profile { get; set; }
        public virtual ICollection<DNN_TabPermission> DNN_TabPermission { get; set; }
        public virtual ICollection<DNN_UserAuthentication> DNN_UserAuthentication { get; set; }
        public virtual ICollection<DNN_UserPortals> DNN_UserPortals { get; set; }
        public virtual ICollection<DNN_UserProfile> DNN_UserProfile { get; set; }
        public virtual ICollection<DNN_UserRoles> DNN_UserRoles { get; set; }
        public virtual ICollection<DNN_UsersOnline> DNN_UsersOnline { get; set; }
        public virtual ICollection<GSS_BranchStaff> GSS_BranchStaff { get; set; }
        public virtual ICollection<GSS_DocumentAttachments> GSS_DocumentAttachments { get; set; }
        public virtual ICollection<GSS_DocumentLog> GSS_DocumentLog { get; set; }
        public virtual ICollection<GSS_DocumentQueues> GSS_DocumentQueues { get; set; }
        public virtual ICollection<GSS_GroupHeads> GSS_GroupHeads { get; set; }
        public virtual ICollection<GSS_HeadsOfOperations> GSS_HeadsOfOperations { get; set; }
        public virtual ICollection<GSS_TeamUsers> GSS_TeamUsers { get; set; }
    }
}
