//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_RoleGroups
    {
        public DNN_RoleGroups()
        {
            this.DNN_Roles = new HashSet<DNN_Roles>();
        }
    
        public int RoleGroupID { get; set; }
        public int PortalID { get; set; }
        public string RoleGroupName { get; set; }
        public string Description { get; set; }
    
        public virtual DNN_Portals DNN_Portals { get; set; }
        public virtual ICollection<DNN_Roles> DNN_Roles { get; set; }
    }
}
