//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNN_vw_Users
    {
        public int UserId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public bool IsSuperUser { get; set; }
        public string Email { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public bool UpdatePassword { get; set; }
        public Nullable<bool> Authorised { get; set; }
    }
}
