//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_Tags
    {
        public GSS_Cheques_Tags()
        {
            this.GSS_Cheques_SupportingDocuments = new HashSet<GSS_Cheques_SupportingDocuments>();
        }
    
        public string TagID { get; set; }
        public string ScanID { get; set; }
        public string Narration { get; set; }
        public string Comments { get; set; }
    
        public virtual GSS_Cheques_Scans GSS_Cheques_Scans { get; set; }
        public virtual ICollection<GSS_Cheques_SupportingDocuments> GSS_Cheques_SupportingDocuments { get; set; }
    }
}
