//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_TeamClusters
    {
        public string TeamClusterID { get; set; }
        public string TeamID { get; set; }
        public string ClusterID { get; set; }
    
        public virtual GSS_Clusters GSS_Clusters { get; set; }
        public virtual GSS_Teams GSS_Teams { get; set; }
    }
}
