//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Clusters
    {
        public GSS_Clusters()
        {
            this.GSS_BusinessOffices = new HashSet<GSS_BusinessOffices>();
            this.GSS_TeamClusters = new HashSet<GSS_TeamClusters>();
        }
    
        public string ClusterID { get; set; }
        public string BankID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
    
        public virtual GSS_Banks GSS_Banks { get; set; }
        public virtual ICollection<GSS_BusinessOffices> GSS_BusinessOffices { get; set; }
        public virtual ICollection<GSS_TeamClusters> GSS_TeamClusters { get; set; }
    }
}
