//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_Queues
    {
        public int AssigneeUserID { get; set; }
        public string WorkflowID { get; set; }
        public string ScanID { get; set; }
        public int ScanStatus { get; set; }
        public int WorkflowItemStatus { get; set; }
        public Nullable<int> WorkflowStatus { get; set; }
    }
}
