//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_ATMCustodians
    {
        public string EntryID { get; set; }
        public int UserID { get; set; }
        public string TerminalID { get; set; }
        public int BOMID { get; set; }
        public int AOMID { get; set; }
        public Nullable<System.Guid> TerminalGUID { get; set; }
    }
}
