//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_TransactionActivityReportView
    {
        public string RegionalBankID { get; set; }
        public string RegionalBankName { get; set; }
        public string BankID { get; set; }
        public string BankName { get; set; }
        public string ClusterID { get; set; }
        public string ClusterName { get; set; }
        public string BusinessOfficeID { get; set; }
        public string SolID { get; set; }
        public string BusinessOfficeName { get; set; }
        public Nullable<int> AO_Received { get; set; }
        public Nullable<int> AO_Pending { get; set; }
        public Nullable<int> AO_In_TAT { get; set; }
        public Nullable<int> AO_Out_TAT { get; set; }
        public Nullable<int> AO_Average { get; set; }
        public Nullable<int> AM_Received { get; set; }
        public Nullable<int> AM_Pending { get; set; }
        public Nullable<int> AM_In_TAT { get; set; }
        public Nullable<int> AM_Out_TAT { get; set; }
        public Nullable<int> AM_Average { get; set; }
        public Nullable<int> LA_Received { get; set; }
        public Nullable<int> LA_Pending { get; set; }
        public Nullable<int> LA_In_TAT { get; set; }
        public Nullable<int> LA_Out_TAT { get; set; }
        public Nullable<int> LA_Average { get; set; }
        public Nullable<int> FT_Received { get; set; }
        public Nullable<int> FT_Pending { get; set; }
        public Nullable<int> FT_In_TAT { get; set; }
        public Nullable<int> FT_Out_TAT { get; set; }
        public Nullable<int> FT_Average { get; set; }
    }
}
