//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Teams_View
    {
        public string TeamID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EarlyAMPro { get; set; }
        public Nullable<int> LateAMPro { get; set; }
        public Nullable<int> EarlyAOPro { get; set; }
        public Nullable<int> LateAOPro { get; set; }
        public Nullable<int> EarlyFTPro { get; set; }
        public Nullable<int> LateFTPro { get; set; }
        public Nullable<int> EarlyLAPro { get; set; }
        public Nullable<int> LateLAPro { get; set; }
        public Nullable<int> EarlyAMSup { get; set; }
        public Nullable<int> LateAMSup { get; set; }
        public Nullable<int> EarlyAOSup { get; set; }
        public Nullable<int> LateAOSup { get; set; }
        public Nullable<int> EarlyFTSup { get; set; }
        public Nullable<int> LateFTSup { get; set; }
        public Nullable<int> EarlyLASup { get; set; }
        public Nullable<int> LateLASup { get; set; }
    }
}
