//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_BusinessOffices
    {
        public GSS_BusinessOffices()
        {
            this.GSS_BranchStaff = new HashSet<GSS_BranchStaff>();
            this.GSS_Cheques_CutOffTimes = new HashSet<GSS_Cheques_CutOffTimes>();
            this.GSS_Cheques_DeliveryNotes = new HashSet<GSS_Cheques_DeliveryNotes>();
            this.GSS_Cheques_Schedules = new HashSet<GSS_Cheques_Schedules>();
            this.GSS_Documents = new HashSet<GSS_Documents>();
        }
    
        public string BusinessOfficeID { get; set; }
        public string ClusterID { get; set; }
        public string Name { get; set; }
        public string SolID { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<GSS_BranchStaff> GSS_BranchStaff { get; set; }
        public virtual GSS_Clusters GSS_Clusters { get; set; }
        public virtual ICollection<GSS_Cheques_CutOffTimes> GSS_Cheques_CutOffTimes { get; set; }
        public virtual ICollection<GSS_Cheques_DeliveryNotes> GSS_Cheques_DeliveryNotes { get; set; }
        public virtual ICollection<GSS_Cheques_Schedules> GSS_Cheques_Schedules { get; set; }
        public virtual ICollection<GSS_Documents> GSS_Documents { get; set; }
    }
}
