//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Documents_View
    {
        public string DocumentID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string BusinessOfficeID { get; set; }
        public int Pages { get; set; }
        public string FileSize { get; set; }
        public int DocumentType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int WorkflowStatus { get; set; }
        public int ApprovalStatus { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string SerialNumber { get; set; }
        public string TransactionID { get; set; }
        public System.DateTime CriticalDate { get; set; }
        public System.DateTime EmergencyDate { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmailAddress { get; set; }
        public Nullable<int> QueueCount { get; set; }
        public System.DateTime DateReviewed { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public int ProcessorID { get; set; }
        public int ReviewerID { get; set; }
    }
}
