//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Banks
    {
        public GSS_Banks()
        {
            this.GSS_Clusters = new HashSet<GSS_Clusters>();
            this.GSS_GroupHeads = new HashSet<GSS_GroupHeads>();
        }
    
        public string BankID { get; set; }
        public string RegionalBankID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
    
        public virtual GSS_RegionalBanks GSS_RegionalBanks { get; set; }
        public virtual ICollection<GSS_Clusters> GSS_Clusters { get; set; }
        public virtual ICollection<GSS_GroupHeads> GSS_GroupHeads { get; set; }
    }
}
