//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_ReturnReasons
    {
        public string EntryID { get; set; }
        public string WorkflowID { get; set; }
        public string Narration { get; set; }
    
        public virtual GSS_Cheques_ScansWorkflows GSS_Cheques_ScansWorkflows { get; set; }
    }
}
