//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Teams
    {
        public GSS_Teams()
        {
            this.GSS_TeamClusters = new HashSet<GSS_TeamClusters>();
            this.GSS_TeamUsers = new HashSet<GSS_TeamUsers>();
        }
    
        public string TeamID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GSS_TeamClusters> GSS_TeamClusters { get; set; }
        public virtual ICollection<GSS_TeamUsers> GSS_TeamUsers { get; set; }
    }
}
