//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_Schedules
    {
        public GSS_Cards_Schedules()
        {
            this.GSS_Cards_Jobs = new HashSet<GSS_Cards_Jobs>();
        }
    
        public int ScheduleID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    
        public virtual ICollection<GSS_Cards_Jobs> GSS_Cards_Jobs { get; set; }
    }
}
