//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_RegionalBanks
    {
        public GSS_RegionalBanks()
        {
            this.GSS_Banks = new HashSet<GSS_Banks>();
            this.GSS_HeadsOfOperations = new HashSet<GSS_HeadsOfOperations>();
        }
    
        public string RegionalBankID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<GSS_Banks> GSS_Banks { get; set; }
        public virtual ICollection<GSS_HeadsOfOperations> GSS_HeadsOfOperations { get; set; }
    }
}
