//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_OUT_CBN_Cheques
    {
        public string ChequeID { get; set; }
        public string ScanID { get; set; }
        public string MicrCode { get; set; }
        public string SortCode { get; set; }
        public string SourceAccount { get; set; }
        public string InstrumentNumber { get; set; }
        public string FrontViewFileName { get; set; }
        public string RearViewFileName { get; set; }
    }
}
