//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_Transactions
    {
        public string ScanID { get; set; }
        public string SolID { get; set; }
        public int Status { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int CompletedBy { get; set; }
        public string AccountName { get; set; }
        public decimal Amount { get; set; }
        public string AccountNumber { get; set; }
        public string Path { get; set; }
        public string PDFFileName { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    }
}
