//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_DeliveryNotes
    {
        public GSS_Cheques_DeliveryNotes()
        {
            this.GSS_Cheques_Details = new HashSet<GSS_Cheques_Details>();
        }
    
        public string DeliveryNoteID { get; set; }
        public string Name { get; set; }
        public string BusinessOfficeID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public int Session { get; set; }
    
        public virtual GSS_BusinessOffices GSS_BusinessOffices { get; set; }
        public virtual ICollection<GSS_Cheques_Details> GSS_Cheques_Details { get; set; }
    }
}
