//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_TeamView
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public int Availability { get; set; }
        public int MaxQueue { get; set; }
        public string Role { get; set; }
        public Nullable<bool> AM { get; set; }
        public Nullable<bool> AO { get; set; }
        public Nullable<bool> LA { get; set; }
        public Nullable<bool> FT { get; set; }
        public Nullable<int> Processed { get; set; }
        public Nullable<int> Rejected { get; set; }
        public Nullable<int> Queued { get; set; }
        public string TeamID { get; set; }
    }
}
