//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_SupportingDocuments
    {
        public string DocumentID { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDateTime { get; set; }
        public string Url { get; set; }
        public string TagID { get; set; }
        public string Name { get; set; }
    
        public virtual GSS_Cheques_Tags GSS_Cheques_Tags { get; set; }
    }
}
