//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_JobTypes
    {
        public int JobTypeID { get; set; }
        public string Name { get; set; }
        public string FriendlyName { get; set; }
        public int StartMinutesFromMidnight { get; set; }
        public bool RerunOnFailure { get; set; }
        public Nullable<int> RerunStartMinutesFromMidnight { get; set; }
        public string DependentOnJobType { get; set; }
        public Nullable<int> DependencyBufferInMinutes { get; set; }
        public string Status { get; set; }
        public bool SendMailOnCompletion { get; set; }
        public Nullable<int> ParentJobTypeID { get; set; }
        public int MaximumAutoReruns { get; set; }
    }
}
