//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_DocumentAttachments
    {
        public string AttachmentID { get; set; }
        public string DocumentID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DNN_Users DNN_Users { get; set; }
        public virtual GSS_Documents GSS_Documents { get; set; }
    }
}
