//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_Details
    {
        public GSS_Cheques_Details()
        {
            this.GSS_Cheques_DeliveryNotes = new HashSet<GSS_Cheques_DeliveryNotes>();
            this.GSS_Cheques_Schedules = new HashSet<GSS_Cheques_Schedules>();
        }
    
        public string ChequeID { get; set; }
        public string ScanID { get; set; }
        public string MicrCode { get; set; }
        public string SortCode { get; set; }
        public string SourceAccount { get; set; }
        public string InstrumentNumber { get; set; }
        public string FrontViewFileName { get; set; }
        public string RearViewFileName { get; set; }
    
        public virtual GSS_Cheques_Scans GSS_Cheques_Scans { get; set; }
        public virtual ICollection<GSS_Cheques_DeliveryNotes> GSS_Cheques_DeliveryNotes { get; set; }
        public virtual ICollection<GSS_Cheques_Schedules> GSS_Cheques_Schedules { get; set; }
    }
}
