//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_Jobs
    {
        public GSS_Cards_Jobs()
        {
            this.GSS_Cards_JobRuns = new HashSet<GSS_Cards_JobRuns>();
        }
    
        public int JobID { get; set; }
        public int ScheduleID { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public int Trials { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartedDateTime { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public string Message { get; set; }
        public Nullable<bool> SendMailOnCompletion { get; set; }
        public Nullable<int> JobTypeID { get; set; }
    
        public virtual ICollection<GSS_Cards_JobRuns> GSS_Cards_JobRuns { get; set; }
        public virtual GSS_Cards_Schedules GSS_Cards_Schedules { get; set; }
    }
}
