//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_ReplacementScans
    {
        public string ReplacementID { get; set; }
        public string OldScanID { get; set; }
        public string NewScanID { get; set; }
        public string Reason { get; set; }
    }
}
