//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_JobRuns
    {
        public int RunID { get; set; }
        public int JobID { get; set; }
        public Nullable<System.DateTime> StartedDateTime { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public bool SendMailOnCompletion { get; set; }
        public System.DateTime DueDateTime { get; set; }
        public int TotalCountEstimate { get; set; }
        public int TotalCountActual { get; set; }
        public int CurrentCount { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual GSS_Cards_Jobs GSS_Cards_Jobs { get; set; }
    }
}
