//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_Terminals
    {
        public string TerminalID { get; set; }
        public string Location { get; set; }
        public string IPAddress { get; set; }
        public string Brand { get; set; }
        public string SolID { get; set; }
        public string Currency { get; set; }
        public string TillAccount { get; set; }
        public Nullable<int> RC { get; set; }
        public Nullable<bool> Offsite { get; set; }
        public Nullable<System.Guid> TerminalGUID { get; set; }
        public string OldTerminalID { get; set; }
    }
}
