//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques
    {
        public GSS_Cheques()
        {
            this.GSS_Cheques_CautionReasons = new HashSet<GSS_Cheques_CautionReasons>();
            this.GSS_Cheques_Logs = new HashSet<GSS_Cheques_Logs>();
            this.GSS_Cheques_RejectionReasons = new HashSet<GSS_Cheques_RejectionReasons>();
        }
    
        public string ChequeID { get; set; }
        public string MicrCode { get; set; }
        public string Schedule { get; set; }
        public string InstrumentNumber { get; set; }
        public string DestinationBankName { get; set; }
        public string DestinationBranchName { get; set; }
        public string DestinationBankSortCode { get; set; }
        public string SourceAccount { get; set; }
        public double Amount { get; set; }
        public string BeneficiaryAccountName { get; set; }
        public string BeneficiaryAccountNumber { get; set; }
        public System.DateTime ValueDate { get; set; }
        public string TransactionType { get; set; }
        public int Status { get; set; }
        public string PresentingBankSortCode { get; set; }
        public string SolID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatorEmail { get; set; }
        public string AuthorizerEmail { get; set; }
        public System.DateTime AuthorizedDateTime { get; set; }
        public string FrontImageFilePath { get; set; }
        public string RearImageFilePath { get; set; }
    
        public virtual ICollection<GSS_Cheques_CautionReasons> GSS_Cheques_CautionReasons { get; set; }
        public virtual ICollection<GSS_Cheques_Logs> GSS_Cheques_Logs { get; set; }
        public virtual ICollection<GSS_Cheques_RejectionReasons> GSS_Cheques_RejectionReasons { get; set; }
    }
}
