//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_Disputes_Logs
    {
        public System.Guid LogID { get; set; }
        public string DisputeID { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public int Status { get; set; }
    
        public virtual GSS_Cards_Disputes_NEW GSS_Cards_Disputes_NEW { get; set; }
    }
}
