//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_Scans
    {
        public GSS_Cheques_Scans()
        {
            this.GSS_Cheques_Details = new HashSet<GSS_Cheques_Details>();
            this.GSS_Cheques_ScansHistories = new HashSet<GSS_Cheques_ScansHistories>();
            this.GSS_Cheques_ScansWorkflows = new HashSet<GSS_Cheques_ScansWorkflows>();
            this.GSS_Cheques_Tags = new HashSet<GSS_Cheques_Tags>();
        }
    
        public string ScanID { get; set; }
        public string SolID { get; set; }
        public int Status { get; set; }
        public string FileName { get; set; }
        public string BatchCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatorID { get; set; }
        public string VersionIdentifier { get; set; }
        public Nullable<int> Version { get; set; }
        public string Path { get; set; }
        public string PDFFileName { get; set; }
        public string SlipFileName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public decimal Amount { get; set; }
        public int LastUserAction { get; set; }
    
        public virtual ICollection<GSS_Cheques_Details> GSS_Cheques_Details { get; set; }
        public virtual ICollection<GSS_Cheques_ScansHistories> GSS_Cheques_ScansHistories { get; set; }
        public virtual ICollection<GSS_Cheques_ScansWorkflows> GSS_Cheques_ScansWorkflows { get; set; }
        public virtual ICollection<GSS_Cheques_Tags> GSS_Cheques_Tags { get; set; }
    }
}
