//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Gasper
    {
        public Nullable<double> S_N { get; set; }
        public int TERMINAL_ID { get; set; }
        public string ATM_NAME { get; set; }
        public string BO_ADDRESS { get; set; }
        public string SOL_ID { get; set; }
        public string BOM { get; set; }
        public string CO { get; set; }
        public string AOM { get; set; }
    }
}
