//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cards_Transactions
    {
        public System.Guid TransactionID { get; set; }
        public string CardNumber { get; set; }
        public string Stan { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionType { get; set; }
        public string TerminalID { get; set; }
        public string JournalExtract { get; set; }
    }
}
