//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_FinacleReportFiles
    {
        public string FinacleReportFileID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string SolID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    }
}
