//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custodians
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Cheques_ScansHistories
    {
        public string HistoryID { get; set; }
        public string ScanID { get; set; }
        public int ActorUserID { get; set; }
        public int Action { get; set; }
        public System.DateTime ActionDateTime { get; set; }
    
        public virtual GSS_Cheques_Scans GSS_Cheques_Scans { get; set; }
    }
}
